#!/bin/bash

#1
#fdisk /dev/sda
#	n p 3 default +300M w

#2
#sudo blkid /dev/sda3 | cut -d "\"" -f2 > UUID_SDA_3

#3
#mkfs.ext4 -b 4096 /dev/sda3

#4
#dumpe2fs -h /dev/sda3 > inf_sda3

#5
#tune2fs -i 2m -C 2 /dev/sda3

#6
#mkdir /mnt/newdisk
#mount -t ext4 /dev/sda3 /mnt/newdisk

#7
#ln -s /mnt/newdisk ~/s_link

#8
#mkdir /mnt/newdisk/folder

#9
#Added to /etc/fstab: /dev/sda3   /mnt/newdisk   ext4   noexec,noatime   0 0

#10
#umount /dev/sda3
#fdisk /dev/sda
#	d 3 
#	n p 3 default +350M NoExt4 w
#reboot
#resize2fs /dev/sda3

#11
#fsck -n /dev/sda3

#12
#fdisk /dev/sda
#	n p 4 default +12M w
#mkfs.ext4 /dev/sda4
#umount /dev/sda3
#mke2fs -O journal_dev /dev/sda4
#mke2fs -t ext4 -J device=/dev/sda4 /dev/sda3

#13
#fdisk /dev/sda
#	d 3 d 4
#	n p 3 default +100M YesExt4
#	n p 4 default +100M

#14
#pvcreate /dev/sda3 /dev/sda4
#vgcreate vg01 /dev/sda3 /dev/sda4
#lvcreate -L180 -n lv01 vg01
#mkfs.ext4 /dev/vg01/lv01
#mkdir /mnt/supernewdisk
#mount /dev/vg01/lv01 /mnt/supernewdisk

#15
#mkdir /mnt/share
#sudo mount.cifs //IP/Lab2 /mnt/share -o user=USER

#16
#Added to /etc/fstab: //IP/Lab2 /mnt/share cifs user=USER,password=PASSWORD,rw,iocharset=utf8 0 0
